// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_i_found_it = "CgkIqJ2C-KgQEAIQDA"; // <GPGSID>
        public const string achievement_diamondsso_many_diamonds = "CgkIqJ2C-KgQEAIQCg"; // <GPGSID>
        public const string achievement_collect_some_diamonds = "CgkIqJ2C-KgQEAIQAQ"; // <GPGSID>
        public const string achievement_behind_the_door = "CgkIqJ2C-KgQEAIQAg"; // <GPGSID>
        public const string leaderboard_cherries = "CgkIqJ2C-KgQEAIQBg"; // <GPGSID>
        public const string achievement_im_so_perceptive = "CgkIqJ2C-KgQEAIQCw"; // <GPGSID>
        public const string achievement_look_out = "CgkIqJ2C-KgQEAIQCQ"; // <GPGSID>
        public const string achievement_theres_must_be_something = "CgkIqJ2C-KgQEAIQAw"; // <GPGSID>
        public const string leaderboard_diamonds = "CgkIqJ2C-KgQEAIQBw"; // <GPGSID>
        public const string achievement_get_some_cherries = "CgkIqJ2C-KgQEAIQAA"; // <GPGSID>
        public const string achievement_get_more_cherries = "CgkIqJ2C-KgQEAIQBA"; // <GPGSID>
        public const string achievement_collect_more_diamonds = "CgkIqJ2C-KgQEAIQBQ"; // <GPGSID>

}

